src/geabbngo/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
from .views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name='home'),
    url(r'^resturents/',include('grabbngoapp.urls', namespace='grabbngoapp')),
]


if settings.DEBUG:
    urlpatterns += (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

src/grabbngoapp/urls.py
from django.conf.urls import url
from .views import GrabnGoDetailView,GrabnGoListView,grabngo_detail_view

urlpatterns = [
  url(r'^$',GrabnGoListView.as_view(), name='list'),
  url(r'^(?P<pk>\d+)/$', GrabnGoDetailView.as_view(), name='detail'),
]

src/grabbngoapp/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.urls import reverse

# Create your models here.

class Resturent(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    content = models.CharField(max_length=120)
    location = models.CharField(max_length=120)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.content)

    def get_absolute_url(self):
        return reverse("grabbngoapp:detail", kwargs={"pk":self.pk})    

src/grabbngoapp/forms.py
from django import forms


from .models import Resturent

class GrabModelForm(forms.ModelForm):
    class Meta:
        model = Resturent
        fields = [
            "user",
            "content" 
        ]
        #exclude = ['user']

    def clean_content(self, *args, **kwargs):
        content = self.cleaned_data.get("content")
        if content == "abc":
            raise forms.ValidationError("Cannot be ABC")
        return content

src/geabbngo/views.py
from django.shortcuts import render


def home(request):
    return render(request, "home.html",{})

src/grabbngoapp/views.py
from django.shortcuts import render,get_object_or_404
from .models import Resturent
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from .mixins import FormUserNeededMixin
# Create your views here.





class GrabnGoDetailView(DetailView):
    queryset = Resturent.objects.all()



class GrabnGoListView(ListView):
    def get_queryset(self, *args, **kwargs):
        qs = Resturent.objects.all()
        print(self.request.GET)
        query = self.request.GET.get("q", None)
        if query is not None:
            qs = qs.filter(
                    Q(content__icontains=query) |
                    Q(user__username__icontains=query) |
                    Q(location__icontains=query)
                    )
        return qs

    def get_context_data(self, *args, **kwargs):
        context = super(GrabnGoListView, self).get_context_data(*args, **kwargs)
        return context


def grabngo_detail_view(request, pk=None): # pk == id
    obj = get_object_or_404(Resturent, pk=pk)
    print(obj)
    context = {
        "object": obj
    }
    return render(request, "grabbngoapp/detail_view.html", context)

src/grabbngoapp/templates/grabbngoapp/list_view.html
{% for object in object_list %}
    <p>{{ object.content }}<br/>
    {{ object.user }}<br/>
    {{ object.timestamp|timesince }} ago</p><br/><br/>
{% empty %}
    <p>No Resturent Listed Yet.</p>
{% endfor %}

src/grabbngoapp/templates/grabbngoapp/resturent_detail.html
{% extends "base.html" %}


{% block content %}

<div class="jumbotron" style="margin-top:8%;">
        <h1 class="display-4">{{ object.location }}</h1>
        <p class="lead">{{ object.content }}</p>
        <hr class="my-4">
        <p>{{ object.user }}</p>
        <a class="btn btn-primary btn-lg" href="#" role="button">{{ object.timestamp|timesince }}</a>
      </div>


{% endblock %}

src/grabbngoapp/templates/grabbngoapp/resturent_list.html
{% extends "base.html" %}

{% block content %}

<div class="row" style="margin-top:8%;">
        {% for object in object_list %}
        <div class="col-sm-4">
          <div class="card">
            <div class="card-body">
              <p class="card-text">{{ object.content }}</p>
              <span>{{object.location}} |  {{ object.user }}</span><br>
              <span>{{ object.timestamp|timesince }} ago</span><br>
              <a href='{{ object.get_absolute_url }}' class="btn btn-primary">View</a>
            </div>
          </div>
        </div>
        {% empty %}
        <p>No resturent listed yet with this address.</p>
        {% endfor %}
      </div>

{% endblock%}

src/grabbngoapp/templates/grabbngoapp/search_form.html
<form method='GET' action='{% url "grabbngoapp:list" %}' class="form-inline my-2 my-lg-0">
    <input type='text' name='q' placeholder='Search Location' value='{{ request.GET.q }}' class="form-control mr-sm-2"/>
    <input type='submit' value='Search' class="btn btn-outline-success my-2 my-sm-0"/>
</form>

src/templates/base.html
{% load static%}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <title>grabbngo-task</title>
  </head>
  <body>
 {% include "navbar.html" %}

    <div class='container'>
        {% block content %}
        {% endblock content %}
  
      </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
  </body>
</html>

src/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="text-center" style="margin-top:20%;">
    <h1>Find Your Resturent | Location Wise Resturent</h1>
    <a class="btn btn-primary btn-lg" href='{% url "grabbngoapp:list" %}'>Find Resturent</a>
</div>

{% endblock%}

src/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="\">GrabbnGo</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href='{% url "grabbngoapp:list" %}'>Resturents <span class="sr-only">(current)</span></a>
        </li>
      </ul>
      {% include "grabbngoapp/search_form.html" %}
    </div>
  </nav>